/*
Aoi.js Functions API

Returns functions information based on the [docs](https://aoi.js.org/)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the FunctionsGet200ResponseInnerTableInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FunctionsGet200ResponseInnerTableInner{}

// FunctionsGet200ResponseInnerTableInner struct for FunctionsGet200ResponseInnerTableInner
type FunctionsGet200ResponseInnerTableInner struct {
	Path *string `json:"path,omitempty"`
	Text *string `json:"text,omitempty"`
	Encoding *string `json:"encoding,omitempty"`
}

// NewFunctionsGet200ResponseInnerTableInner instantiates a new FunctionsGet200ResponseInnerTableInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFunctionsGet200ResponseInnerTableInner() *FunctionsGet200ResponseInnerTableInner {
	this := FunctionsGet200ResponseInnerTableInner{}
	return &this
}

// NewFunctionsGet200ResponseInnerTableInnerWithDefaults instantiates a new FunctionsGet200ResponseInnerTableInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFunctionsGet200ResponseInnerTableInnerWithDefaults() *FunctionsGet200ResponseInnerTableInner {
	this := FunctionsGet200ResponseInnerTableInner{}
	return &this
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *FunctionsGet200ResponseInnerTableInner) GetPath() string {
	if o == nil || IsNil(o.Path) {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FunctionsGet200ResponseInnerTableInner) GetPathOk() (*string, bool) {
	if o == nil || IsNil(o.Path) {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *FunctionsGet200ResponseInnerTableInner) HasPath() bool {
	if o != nil && !IsNil(o.Path) {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *FunctionsGet200ResponseInnerTableInner) SetPath(v string) {
	o.Path = &v
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *FunctionsGet200ResponseInnerTableInner) GetText() string {
	if o == nil || IsNil(o.Text) {
		var ret string
		return ret
	}
	return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FunctionsGet200ResponseInnerTableInner) GetTextOk() (*string, bool) {
	if o == nil || IsNil(o.Text) {
		return nil, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *FunctionsGet200ResponseInnerTableInner) HasText() bool {
	if o != nil && !IsNil(o.Text) {
		return true
	}

	return false
}

// SetText gets a reference to the given string and assigns it to the Text field.
func (o *FunctionsGet200ResponseInnerTableInner) SetText(v string) {
	o.Text = &v
}

// GetEncoding returns the Encoding field value if set, zero value otherwise.
func (o *FunctionsGet200ResponseInnerTableInner) GetEncoding() string {
	if o == nil || IsNil(o.Encoding) {
		var ret string
		return ret
	}
	return *o.Encoding
}

// GetEncodingOk returns a tuple with the Encoding field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FunctionsGet200ResponseInnerTableInner) GetEncodingOk() (*string, bool) {
	if o == nil || IsNil(o.Encoding) {
		return nil, false
	}
	return o.Encoding, true
}

// HasEncoding returns a boolean if a field has been set.
func (o *FunctionsGet200ResponseInnerTableInner) HasEncoding() bool {
	if o != nil && !IsNil(o.Encoding) {
		return true
	}

	return false
}

// SetEncoding gets a reference to the given string and assigns it to the Encoding field.
func (o *FunctionsGet200ResponseInnerTableInner) SetEncoding(v string) {
	o.Encoding = &v
}

func (o FunctionsGet200ResponseInnerTableInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FunctionsGet200ResponseInnerTableInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Path) {
		toSerialize["path"] = o.Path
	}
	if !IsNil(o.Text) {
		toSerialize["text"] = o.Text
	}
	if !IsNil(o.Encoding) {
		toSerialize["encoding"] = o.Encoding
	}
	return toSerialize, nil
}

type NullableFunctionsGet200ResponseInnerTableInner struct {
	value *FunctionsGet200ResponseInnerTableInner
	isSet bool
}

func (v NullableFunctionsGet200ResponseInnerTableInner) Get() *FunctionsGet200ResponseInnerTableInner {
	return v.value
}

func (v *NullableFunctionsGet200ResponseInnerTableInner) Set(val *FunctionsGet200ResponseInnerTableInner) {
	v.value = val
	v.isSet = true
}

func (v NullableFunctionsGet200ResponseInnerTableInner) IsSet() bool {
	return v.isSet
}

func (v *NullableFunctionsGet200ResponseInnerTableInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFunctionsGet200ResponseInnerTableInner(val *FunctionsGet200ResponseInnerTableInner) *NullableFunctionsGet200ResponseInnerTableInner {
	return &NullableFunctionsGet200ResponseInnerTableInner{value: val, isSet: true}
}

func (v NullableFunctionsGet200ResponseInnerTableInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFunctionsGet200ResponseInnerTableInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


